### ISSUE TITLE
Elements of theme applied even when theme is not selected

### ISSUE THREAD

**Issue by pinkneonsign** [timkpaine/jupyterlab_miami_nights#35]
Gradient background and certain fonts remain applied to JupyterLab even when using any other theme.

**To Reproduce**
Installed via JL extension manager and rebuild. Uninstalling and building via `jupyter labextension uninstall` and subsequent `install` provides no solution.

**Screenshots**
Will add screenshots soon. See [_Theme is applied to JupyterLab's UI even when it is not the selected theme #18_](https://github.com/yeebc/jupyterlab-neon-theme/issues/18) in **jupyterlab-neon-theme** for similar behaviour.

**Comment by fny** [comment]
I have no relationship to this repo, but this is clearly a bug with Jupyter Lab. You should report it there.

**Comment by timkpaine** [comment]
this should've been fixed in https://github.com/timkpaine/jupyterlab_miami_nights/pull/19#issuecomment-859694979
