### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by lifelonglearning0129** [timkpaine/jupyterlab_miami_nights#75]
How to install? Can it be installed in JupyterLab 4.x?

**Comment by timkpaine** [comment]
https://pypi.org/project/jupyterlab-miami-nights/

```bash
pip install jupyterlab-miami-nights
```

yes

**Comment by raffaelemancuso** [comment]
> https://pypi.org/project/jupyterlab-miami-nights/
> 
> pip install jupyterlab-miami-nights
> 
> yes

The README doesn't say that
